name: Dev Deployment
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy it to dev baby
    runs-on: ubuntu-latest
    steps:
      - name: Deploy develop branch
        run: echo Deploying develop branch
